version: '3.9'
services:
  nonolerobot:
    image: nonolerobot
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mariadb

  mariadb:
      container_name: db_nono
      image: mariadb:latest
      restart: on-failure
      ports:
        - 3306:3306
      environment:
        MARIADB_DATABASE: ${MARIADB_DATABASE}
        MARIADB_ROOT_USER: ${MARIADB_ROOT_USER}
        MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
        MARIADB_USER: ${MARIADB_USER}
        MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      volumes:
        - ./mariadb:/var/lib/mysql
